language: cpp
dist: trusty
os:
    -   linux
compiler:
    -   clang
    -   gcc
sudo: required
matrix:
    exclude:
        -   os: linux
    include:
        -   os: linux
            compiler: clang
            env: COMPILER="clang++-3.8 -stdlib=libc++" USE_BOOST_FUTURE=0 USE_ADDRESS_SANITIZER=0 PATCH_ASIO=1
            addons: &clang_addons
                apt:
                    sources:
                        -   llvm-toolchain-precise-3.8
                    packages:
                        -   libboost-all-dev
                        -   libcurl4-openssl-dev
                        -   clang-3.8
                        -   libc++-dev
        -   os: linux
            compiler: clang
            env: COMPILER="clang++-3.8 -stdlib=libc++" USE_BOOST_FUTURE=1 USE_ADDRESS_SANITIZER=0 PATCH_ASIO=1
            addons: *clang_addons
        -   os: linux
            compiler: gcc
            env: COMPILER=g++-5 USE_BOOST_FUTURE=0 USE_ADDRESS_SANITIZER=1
            addons: &gcc5_addons
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   libboost-all-dev
                        -   libcurl4-openssl-dev
                        -   g++-5
        -   os: linux
            compiler: gcc
            env: COMPILER=g++-5 USE_BOOST_FUTURE=1 USE_ADDRESS_SANITIZER=1
            addons: *gcc5_addons
        -   os: linux
            compiler: gcc
            env: COMPILER=g++-6 USE_BOOST_FUTURE=0 USE_ADDRESS_SANITIZER=0
            addons: &gcc6_addons
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   libboost-all-dev
                        -   libcurl4-openssl-dev
                        -   g++-6
        -   os: linux
            compiler: gcc
            env: COMPILER=g++-6 USE_BOOST_FUTURE=1 USE_ADDRESS_SANITIZER=0
            addons: *gcc6_addons
before_install:
    -   git clone https://github.com/philsquared/Catch.git
    -   sudo cp ./Catch/single_include/catch.hpp /usr/local/include
    -   'if [ ${PATCH_ASIO} ]; then sudo sed -i -r "s/^#include <cstddef>/#include <stddef.h>/g" /usr/include/boost/asio/local/detail/endpoint.hpp; fi'
script:
    -   export CXX=${COMPILER}
    -   grep "define BOOST_LIB_VERSION" < /usr/include/boost/version.hpp
    -   cmake . -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_FUTURE=${USE_BOOST_FUTURE} -DUSE_ADDRESS_SANITIZER=${USE_ADDRESS_SANITIZER}
    -   make VERBOSE=1